 var itemData = {
	 bg1:{
		name: 'Ryan Dungey 6V Moto Bike',
		price: 70.00,
		quantity:0.00,
		cost:0.00,
		type: 'Baby Gear',
		describe: 'This 4-stage tub, with portable motorized shower unit',
		image:'images/motobike.jpg',
	},
	 bg2:{
		name: 'Graco Car Seat',
		price: 140.00,
		quantity:0.00,
		cost:0.00,
		type: 'Baby Gear',
		describe: 'Graco® Contender Convertible Car Seat - Chili Red',
		image:'images/carseat.jpg',
	},
	 bg3:{
		name: 'Summer Infant® Toddler Bath Center & Shower',
		price: 35.00,
		quantity:0.00,
		cost:0.00,
		type: 'Baby Gear',
		describe: 'This 4-stage tub, with portable motorized shower unit',
		image:'images/babytub.jpg',
	},
	 bg4:{
		name: 'Graco® Stroller',
		price: 100.00,
		quantity:0.00,
		cost:0.00,
		type: 'Baby Gear',
		describe: 'Graco® Verb Click Connect™ Stroller - Sapphire',
		image:'images/canvas2.jpg',
	},
	 bg5:{
		name: 'Graco® Blossom 4-in-1 High Chair',
		price: 100.00,
		quantity:0.00,
		cost:0.00,
		type: 'Baby Gear',
		describe: 'raco® Blossom 4-in-1 High Chair - Nyssa',
		image:'images/canvas3.jpg',
	},
	bg6:{
		name: 'Disney Minni Mouse Playard',
		price: 130.00,
		quantity:0.00,
		cost:0.00,
		type: 'Baby Gear',
		describe: 'Disney Sweet Wonder Minnie Mouse Playard. It features a newborn bassinet, breathable mesh, easy-clean.',
		image:'images/playard.jpg',
	},
	 
	 
	 el1:{
		name: 'Jensen Bluetooth Music System',
		price: 160.00,
		quantity:0.00,
		cost:0.00,
		type: 'Electronics',
		describe: '3-Speed Stereo Turntable with 3CD Changer and Dual Cassette Deck',
		image:'images/jensen-stereo-systems.jpg',
	},
	el2:{
		name: 'Garmin Drive 51 GPS Navigator',
		price: 130.00,
		quantity:0.00,
		cost:0.00,
		type: 'Electronics',
		describe: 'Navigator with Driver Alert',
		image:'images/garmin-gps-navigation.jpg',
	},
	cl1:{
		name: 'C9 Champion® Ebony Heather Jacket',
		price: 42.00,
		quantity:0.00,
		cost:0.00,
		type: 'Clothing',
		describe: 'Ladies Plus Size Cardio Jacket',
		image:'images/womens-jacket.jpg',
	},
	cl2:{
		name: 'C9 Champion® Sweater',
		price: 35.00,
		quantity:0.00,
		cost:0.00,
		type: 'Clothing',
		describe: 'Ladies Sweater Fleece Full Zip',
		image:'images/fleece-sweater.jpg',
	},
	cl3:{
		name: 'Universal Thread™ Beanie',
		price: 17.00,
		quantity:0.00,
		cost:0.00,
		type: 'Clothing',
		describe: 'Ladies Fleece Lined Knit Ribbed Pom Beanie',
		image:'images/womens-beanie.jpg',
	},
	cl4:{
		name: 'DENIZEN® Jeans',
		price: 25.00,
		quantity:0.00,
		cost:0.00,
		type: 'Clothing',
		describe: 'DENIZEN® from Levis® Relaxed Fit 285™ Marine Blue',
		image:'images/mens-jeans.jpg',
	},
	cl5:{
		name: 'Hanes Premium® Mens Socks',
		price: 14.00,
		quantity:0.00,
		cost:0.00,
		type: 'Clothing',
		describe: 'Hanes Premium® Mens 6pk Xtemp Cool No Show Socks',
		image:'images/mens-socks.jpg',
	},
	el3:{
		name: 'Dremel 3D Printer',
		price: 600.00,
		quantity:0.00,
		cost:0.00,
		type: 'Electronics',
		describe: 'Digilab 3D20 Idea Builder 3D Printer for Hobbyists and Home Users',
		image:'images/dremel-3d-printers.jpg',
	},
	el4:{
		name: 'Optoma 3D Projector',
		price: 1399.00,
		quantity:0.00,
		cost:0.00,
		type: 'Electronics',
		describe: '1600 x 1200 DLP Full-3D Multimedia Projector with 6000 Lumens',
		image:'images/optoma-projectors.jpg',
	},
	el5:{
		name: 'Samsung 43" LED TV',
		price: 280.00,
		quantity:0.00,
		cost:0.00,
		type: 'Electronics',
		describe: 'Samsung - 43" Class - LED - NU6900 Series - 2160p - Smart - 4K UHD TV ',
		image:'images/samsung-uhd-tv.jpg',
	},
	 
	ha1:{
		name: 'Whirpool Refrigerator',
		price: 1498.00,
		quantity:0.00,
		cost:0.00,
		type: 'Home Appliances',
		describe: 'Whirpool 25 cu. ft French Door Refrigetor',
		image:'images/whirlpool-french-door-refrigerators.jpg',
	},
	ha2:{
		name: 'Samsung Gas Range',
		price: 598.00,
		quantity:0.00,
		cost:0.00,
		type: 'Home Appliances',
		describe: 'Samsung Self-Cleaning Sainless Steel Gas Range',
		image:'images/samsung-gas-ranges.jpg',
	},
	ha3:{
	name: 'Instant Pot',
	price: 70.00,
	quantity:0.00,
	type: 'Home Appliances',
	describe: 'Instant Pot Duo 6qt 7-in-1 Pressure Cooker',
	image:'images/instant-pot.jpg',
  },
  ha4:{
  	name: 'LG Countertop Microwave',
  	price: 132.00,
  	quantity:0.00,
  	cost:0.00,
  	type: 'Home Appliances',
  	describe: 'LG 0.9 cu ft Countertop Microwave',
  	image: 'images/countertop-microwave.jpg',
  },
  ha5:{
  	name: 'Ninja Pro Kitchen System',
  	price: 160.00,
  	quantity:0.00,
  	cost:0.00,
  	type: 'Home Appliances',
  	describe: 'Ninja Professional 1200W Kitchen System',
  	image: 'images/ninja-blender.jpg',
  },
  ty1:{
    name: 'Barbie Dreamhouse',
    price: 180.00,
    quantity:0.00,
    cost:0.00,
    type: 'Toys',
    describe: 'Barbie Dreamhouse Playset',
    image:'images/barbie-dreamhouse.jpg',
  },
  ty2:{
    name: 'Fingerlings Hugs',
    price: 30.00,
    quantity:0.00,
    cost:0.00,
    type: 'Toys',
    describe: 'Friendly Interactive Plush Monkey',
    image:'images/fingerlings-hugs.jpg',
  },
  ty3:{
	  name: 'Lego Harry Potter',
	  price: 100.00,
	  quantity:0.00,
	  cost:0.00,
	  type: 'Toys',
	  describe: 'LEGO Harry Potter Hogwarts Great Hall',
	  image:'images/lego-harry-potter.jpg',
  },
  ty4:{
	  name: 'Fisher Price Rocktopus',
	  price: 60.00,
	  quantity:0.00,
	  cost:0.00,
	  type: 'Toys',
	  describe: 'Fisher-Price Think and Learn Rocktopus',
	  image: 'images/fisher-price-rocktopus.jpg',
	  },
  ty5:{
	  name: 'Hot Wheels Track Set',
	  price: 50.00,
	  quantity:0.00,
	  cost:0.00,
	  type: 'Toys',
	  describe: 'Hot Wheels Corkscrew Crash Trackset',
	  image: 'images/hot-wheels.jpg',
  }
  };
