reviewArray=[
  {id:"bg1", review:"This is a very fantastic product"},
  {id:"bg1", review:"The service was good but product not as expected"},
  {id:"bg1", review:" A very delightful experience and the product was wonderful"},
  {id:"bg2", review:"This is a great product"},
  {id:"bg2", review:"This is a cheap product"},
  {id:"bg3", review:"This is a reliable product"},
  {id:"bg3", review:"The service was good but product not as expected"},
  {id:"bg3", review:" Am unhappy and the product was terrible"},
  {id:"bg4", review:"This is a good product am happy"},
  {id:"bg4", review:"This is an excellent product"},
  {id:"bg4", review:"This is a very fantastic product"},
  {id:"bg5", review:"The service was good love this product"},
  {id:"bg5", review:" A very delightful and the product worked well"},
  {id:"bg5", review:"This is a defective product"},
  {id:"bg5", review:"This is an excellent product"},
  {id:"cl1", review:"This is a very fantastic product"},
  {id:"cl1", review:"The service was good but product not as expected"},
  {id:"cl1", review:" A very delightful experience and the product was wonderful"},
  {id:"cl2", review:"This is a great product"},
  {id:"cl2", review:"This is a cheap product"},
  {id:"cl3", review:"This is a reliable product"},
  {id:"cl3", review:"The service was good but product not as expected"},
  {id:"cl3", review:" Am unhappy and the product was terrible"},
  {id:"cl4", review:"This is a good product am happy"},
  {id:"cl4", review:"This is an excellent product"},
  {id:"cl4", review:"This is a very fantastic product"},
  {id:"cl5", review:"The service was good love this product"},
  {id:"cl5", review:" A very delightful and the product worked well"},
  {id:"cl5", review:"This is a defective product"},
  {id:"cl5", review:"This is an excellent product"},
  {id:"el1", review:"This is a very fantastic product"},
  {id:"el1", review:"The service was good but product not as expected"},
  {id:"el1", review:" A very delightful experience and the product was wonderful"},
  {id:"el2", review:"This is a great product"},
  {id:"el2", review:"This is a cheap product"},
  {id:"el3", review:"This is a reliable product"},
  {id:"el3", review:"The service was good but product not as expected"},
  {id:"el3", review:" Am unhappy and the product was terrible"},
  {id:"el4", review:"This is a good product am happy"},
  {id:"el4", review:"This is an excellent product"},
  {id:"el4", review:"This is a very fantastic product"},
  {id:"el5", review:"The service was good love this product"},
  {id:"el5", review:" A very delightful and the product worked well"},
  {id:"el5", review:"This is a defective product"},
  {id:"el5", review:"This is an excellent product"},
  {id:"ha1", review:"This is a very wonderful product"},
  {id:"ha1", review:"The service was good but product not as expected"},
  {id:"ha1", review:" A very delightful experience and the product was wonderful"},
  {id:"ha1", review:"This is a really nice fridge. so our new one is like heaven."},
  {id:"ha1", review:"The freezer door is defective.  Very disappointed"},
  {id:"ha2", review:"The service was good but product not as expected"},
  {id:"ha2", review:" A very delightful experience and the product was wonderful"},
  {id:"ha2", review:"This is a extremely  good product"},
  {id:"ha2", review:"This is a very fantastic product"},
  {id:"ha2", review:"The service was good but product not as expected"},
  {id:"ha3", review:" A very delightful experience and the product was wonderful"},
  {id:"ha3", review:"This is a extremely  good product"},
  {id:"ha3", review:"This is a very fantastic product"},
  {id:"ha3", review:"The service was good but product not as expected"},
  {id:"ha3", review:" A very delightful experience and the product was wonderful"},
  {id:"ha4", review:"This is a extremely  good product"},
  {id:"ha4", review:"This is a very fantastic product"},
  {id:"ha4", review:"The service was good but product not as expected"},
  {id:"ha4", review:" A very delightful experience and the product was wonderful"},
  {id:"ha4", review:"This is a extremely  good product"},
  {id:"ha5", review:"This is a very fantastic product"},
  {id:"ha5", review:"The service was good but product not as expected"},
  {id:"ha5", review:" A very delightful experience and the product was wonderful"},
  {id:"ha5", review:"This is a extremely  good product"},
  {id:"ha5", review:"This is a extremely  good product"},
  {id:"ty1", review:"This is a very fantastic product"},
  {id:"ty1", review:"The service was good but product not as expected"},
  {id:"ty1", review:" A very delightful experience and the product was wonderful"},
  {id:"ty2", review:"This is a great product"},
  {id:"ty2", review:"This is a cheap product"},
  {id:"ty3", review:"This is a reliable product"},
  {id:"ty3", review:"The service was good but product not as expected"},
  {id:"ty3", review:" Am unhappy and the product was terrible"},
  {id:"ty4", review:"This is a good product am happy"},
  {id:"ty4", review:"This is an excellent product"},
  {id:"ty4", review:"This is a very fantastic product"},
  {id:"ty5", review:"The service was good love this product"},
  {id:"ty5", review:" A very delightful and the product worked well"},
  {id:"ty5", review:"This is a defective product"},
  {id:"ty5", review:"This is an excellent product"},


];
